### ISSUE TITLE
[BUG]: Code-Server WebSocket close with status code 1006

### ISSUE THREAD

**Issue by pyromiko** [azukaar/Cosmos-Server#164]
### What happened?

When i install code-server with url https://my_url.ddns.net:8443 and try to open it got to https://my_url.ddns.net:8443/?folder=/workspace and get error "An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: WebSocket close with status code 1006)"

![image](https://github.com/azukaar/Cosmos-Server/assets/35033939/8fa8d328-221a-4a88-ad20-a2f676fc3fce)

### What should have happened?

seems to had some websocket issue...

### How to reproduce the bug?

1. install code-server with the url on the port you already foward
![image](https://github.com/azukaar/Cosmos-Server/assets/35033939/d8c4f07f-0d31-4e0d-b951-21fb1059eff3)
2. try to open code-server

### Relevant log output

```shell
2023-12-26 01:45:04
 [01:45:04] Extension host agent started.
2023-12-26 01:45:08
 [2023-12-26T01:45:08.732Z] error Failed to get latest version [38;2;140;140;140m{"error":"Unsupported protocol for proxy URL: my_changed_url_example.ddns.net:8443"}
2023-12-26 01:45:25
 [2023-12-26T01:45:25.630Z] error Failed to get latest version [38;2;140;140;140m{"error":"Unsupported protocol for proxy URL: my_changed_url_example.ddns.net:8443"}
2023-12-26 01:45:26
 File not found: /app/code-server/lib/vscode/extensions/emmet/dist/browser/emmetBrowserMain.js
2023-12-26 01:45:26
 File not found: /app/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
2023-12-26 01:45:26
 File not found: /app/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
2023-12-26 01:46:09
 Error: Unexpected SIGPIPE
2023-12-26 01:46:09
     at process. (/app/code-server/lib/vscode/out/bootstrap.js:1:471)
2023-12-26 01:46:09
     at process.emit (node:events:525:35)
2023-12-26 01:46:09
 [01:46:09] Error: Unexpected SIGPIPE
2023-12-26 01:46:09
     at process. (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:180:6104)
2023-12-26 01:46:09
     at process.emit (node:events:525:35)
2023-12-26 01:48:31
 [2023-12-26T01:48:31.319Z] error Failed to get latest version [38;2;140;140;140m{"error":"Unsupported protocol for proxy URL: my_changed_url_example.ddns.net:8443"}
2023-12-26 01:48:32
 File not found: /app/code-server/lib/vscode/extensions/emmet/dist/browser/emmetBrowserMain.js
2023-12-26 01:48:32
 File not found: /app/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
2023-12-26 01:48:32
 File not found: /app/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
2023-12-26 01:48:57
 [2023-12-26T01:48:57.275Z] error Failed to get latest version [38;2;140;140;140m{"error":"Unsupported protocol for proxy URL: my_changed_url_example.ddns.net:8443"}
2023-12-26 01:48:58
 File not found: /app/code-server/lib/vscode/extensions/emmet/dist/browser/emmetBrowserMain.js
2023-12-26 01:48:58
 File not found: /app/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
2023-12-26 01:48:58
 File not found: /app/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
```

### System details

- OS: debian
- Browser chrome,firefox
- Version: any

**Comment by azukaar** [comment]
Make sure you set the PROXY_DOMAIN env with the right URL on the code server container

**Comment by pyromiko** [comment]
Already have it:

![image](https://github.com/azukaar/Cosmos-Server/assets/35033939/6f53df1e-7e5f-418e-88a9-49bfe21d8eb5)

**Comment by pyromiko** [comment]
sorry to ask: why is closed since the problem is reproductible? is there a way to reopen since my last message?

**Comment by neight-allen** [comment]
I'm also having this issue using a LAN hostname. PROXY_DOMAIN env is set correctly.
