### ISSUE TITLE
[BUG]: piped from Servapp doesn't work

### ISSUE THREAD

**Issue by ivanswip** [azukaar/Cosmos-Server#308]
### What happened?

Piped from Servapp doesn't work

### What should have happened?

the page should open and the video should load

### How to reproduce the bug?

1. install piped from servapp
2. go to https://piped.test.com

### Relevant log output

```shell
results:1 Access to fetch at 'https://pipedapi.test.com/config' from origin 'https://piped.test.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'pipedapi.test.com'. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.js:63 
        
        
       GET https://pipedapi.test.com/config net::ERR_FAILED 502 (Bad Gateway)
fetchJson @ main.js:63
fetchAuthConfig @ NavBar.vue:202
mounted @ NavBar.vue:161
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
W @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
I_.t.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.js:640
Show 8 more frames
Show less
results:1 Access to fetch at 'https://pipedapi.test.com/config' from origin 'https://piped.test.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'pipedapi.test.com'. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.js:63 
        
        
       GET https://pipedapi.test.com/config net::ERR_FAILED 502 (Bad Gateway)
fetchJson @ main.js:63
fetchConfig @ FooterComponent.vue:44
mounted @ FooterComponent.vue:40
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
W @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
I_.t.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.js:640
Show 8 more frames
Show less
main.js:63 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (main.js:63:20)
    at Proxy.fetchAuthConfig (NavBar.vue:202:18)
    at Proxy.mounted (NavBar.vue:161:14)
    at runtime-core.esm-bundler.js:1808:40
    at Xt (runtime-core.esm-bundler.js:195:19)
    at ot (runtime-core.esm-bundler.js:202:17)
    at Eo.t.__weh.t.__weh (runtime-core.esm-bundler.js:1788:19)
    at dc (runtime-core.esm-bundler.js:379:35)
    at W (runtime-core.esm-bundler.js:5805:25)
    at mount (runtime-core.esm-bundler.js:3062:20)
fetchJson @ main.js:63
fetchAuthConfig @ NavBar.vue:202
mounted @ NavBar.vue:161
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
W @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
I_.t.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.js:640
Promise.then (async)
fetchAuthConfig @ NavBar.vue:202
mounted @ NavBar.vue:161
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
W @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
I_.t.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.js:640
Show 16 more frames
Show less
main.js:63 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (main.js:63:20)
    at Proxy.fetchConfig (FooterComponent.vue:44:18)
    at Proxy.mounted (FooterComponent.vue:40:14)
    at runtime-core.esm-bundler.js:1808:40
    at Xt (runtime-core.esm-bundler.js:195:19)
    at ot (runtime-core.esm-bundler.js:202:17)
    at Eo.t.__weh.t.__weh (runtime-core.esm-bundler.js:1788:19)
    at dc (runtime-core.esm-bundler.js:379:35)
    at W (runtime-core.esm-bundler.js:5805:25)
    at mount (runtime-core.esm-bundler.js:3062:20)
fetchJson @ main.js:63
fetchConfig @ FooterComponent.vue:44
mounted @ FooterComponent.vue:40
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
W @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
I_.t.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.js:640
Promise.then (async)
fetchConfig @ FooterComponent.vue:44
mounted @ FooterComponent.vue:40
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
W @ runtime-core.esm-bundler.js:5805
mount @ runtime-core.esm-bundler.js:3062
I_.t.mount @ runtime-dom.esm-bundler.js:1530
(anonymous) @ main.js:640
Show 16 more frames
Show less
results:1 Access to fetch at 'https://pipedapi.test.com/search?q=linux&filter=all' from origin 'https://piped.test.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains the invalid value 'pipedapi.test.com'. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.js:63 
        
        
       GET https://pipedapi.test.com/search?q=linux&filter=all net::ERR_FAILED 502 (Bad Gateway)
fetchJson @ main.js:63
fetchResults @ SearchResults.vue:76
updateResults @ SearchResults.vue:83
mounted @ SearchResults.vue:56
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
_c @ runtime-core.esm-bundler.js:415
Promise.then (async)
fc @ runtime-core.esm-bundler.js:319
ho @ runtime-core.esm-bundler.js:313
L @ runtime-core.esm-bundler.js:6117
Hs @ reactivity.esm-bundler.js:262
Yl @ reactivity.esm-bundler.js:306
Hr @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
U @ vue-router.mjs:3460
(anonymous) @ vue-router.mjs:3325
Promise.then (async)
x @ vue-router.mjs:3292
O @ vue-router.mjs:3217
install @ vue-router.mjs:3659
use @ runtime-core.esm-bundler.js:2984
(anonymous) @ main.js:638
Show 19 more frames
Show less
main.js:63 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (main.js:63:20)
    at Proxy.fetchResults (SearchResults.vue:76:37)
    at Proxy.updateResults (SearchResults.vue:83:33)
    at Proxy.mounted (SearchResults.vue:56:14)
    at runtime-core.esm-bundler.js:1808:40
    at Xt (runtime-core.esm-bundler.js:195:19)
    at ot (runtime-core.esm-bundler.js:202:17)
    at Eo.t.__weh.t.__weh (runtime-core.esm-bundler.js:1788:19)
    at dc (runtime-core.esm-bundler.js:379:35)
    at _c (runtime-core.esm-bundler.js:415:5)
fetchJson @ main.js:63
fetchResults @ SearchResults.vue:76
updateResults @ SearchResults.vue:83
mounted @ SearchResults.vue:56
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
_c @ runtime-core.esm-bundler.js:415
Promise.then (async)
updateResults @ SearchResults.vue:83
mounted @ SearchResults.vue:56
(anonymous) @ runtime-core.esm-bundler.js:1808
Xt @ runtime-core.esm-bundler.js:195
ot @ runtime-core.esm-bundler.js:202
Eo.t.__weh.t.__weh @ runtime-core.esm-bundler.js:1788
dc @ runtime-core.esm-bundler.js:379
_c @ runtime-core.esm-bundler.js:415
Promise.then (async)
fc @ runtime-core.esm-bundler.js:319
ho @ runtime-core.esm-bundler.js:313
L @ runtime-core.esm-bundler.js:6117
Hs @ reactivity.esm-bundler.js:262
Yl @ reactivity.esm-bundler.js:306
Hr @ reactivity.esm-bundler.js:1071
set value @ reactivity.esm-bundler.js:1118
U @ vue-router.mjs:3460
(anonymous) @ vue-router.mjs:3325
Promise.then (async)
x @ vue-router.mjs:3292
O @ vue-router.mjs:3217
install @ vue-router.mjs:3659
use @ runtime-core.esm-bundler.js:2984
(anonymous) @ main.js:638
Show 25 more frames
Show less
```

### System details

Any Browser

**Comment by azukaar** [comment]
Thanks for the isssue
in order to keep this repository about Cosmos only, could you please open this ticket in the repository of the apps please?
it's https://github.com/azukaar/cosmos-servapps-official
thanks
