### ISSUE TITLE
[BUG]: Cosmos Server crashes when encoutering capture group in route path regex

### ISSUE THREAD

**Issue by jwr1** [azukaar/Cosmos-Server#59]
### What happened?

While working on the Collabora config, I accidentally used a capture group in the route path. When I saved, the UI became unresponsive and I realized the server completely crashed. I was unable to restart the server until I manually fixed the route in the `/var/lib/cosmos/cosmos.config.json` file.

### What should have happened?

Probably just an error message should pop up in the UI when saving, instead of crashing the whole server.

### How to reproduce the bug?

1. Create a new URL route
2. Set the path prefix to `/(.)` (or anything with a regular capture group).
3. Notice that the UI is unresponsive and the server has crashed

### Relevant log output

```shell
panic: route /cool/{path:(.*)}/ws contains capture groups in its regexp. Only non-capturing groups are accepted: e.g. (?:pattern) instead of (pattern)

goroutine 1 [running]:
github.com/gorilla/mux.newRouteRegexp({0x4000664840, 0x14}, 0x2, {0x0?, 0x0?})
        /home/circleci/.go_workspace/pkg/mod/github.com/gorilla/mux@v1.8.0/regexp.go:135 +0x9c0
github.com/gorilla/mux.(*Route).addRegexpMatcher(0x40002c4780, {0x4000664840?, 0x0?}, 0x2)
        /home/circleci/.go_workspace/pkg/mod/github.com/gorilla/mux@v1.8.0/route.go:186 +0x104
github.com/gorilla/mux.(*Route).PathPrefix(...)
        /home/circleci/.go_workspace/pkg/mod/github.com/gorilla/mux@v1.8.0/route.go:370
github.com/azukaar/cosmos-server/src/proxy.RouterGen({{0x4000664810, 0x13}, {0x4000595e30, 0x9}, 0x1, {0x4000664828, 0x12}, 0x1, {0x4000664840, 0x14}, ...}, ...)
        /home/circleci/project/src/proxy/routerGen.go:66 +0x27c
github.com/azukaar/cosmos-server/src/proxy.BuildFromConfig(0x1ab0ce2?, {{0x40002b4a80?, 0x1eec300?, 0x400054c108?}})
        /home/circleci/project/src/proxy/buildFromConfig.go:18 +0xe8
main.InitServer()
        /home/circleci/project/src/httpServer.go:356 +0x11dc
main.StartServer()
        /home/circleci/project/src/httpServer.go:378 +0x24
main.main()
        /home/circleci/project/src/index.go:47 +0x2e4
```

### System details

- OS: Arch Linux
- Browser: Firefox
- Version: 0.9.13

**Comment by azukaar** [comment]
if you want to use REGEX inthe path please follow this doc:
https://github.com/gorilla/mux#examples

**Comment by jwr1** [comment]
@vrijsinghani, unfortunately, I never was able to get Collabora working behind cosmos. I tried multiple different things and was debugging for many hours, but I never figured out the problem. Eventually, I just gave up on cosmos; now I have everything behind caddy instead (which Collabora works fine with).

**Comment by vrijsinghani** [comment]
@azukaar , thanks for the reply.  I tried to read through the doc you linked to, but failed to comprehend how it would be applied in the context of path prefix line entry in the url setup page.  Could you just provide one example entry of a regex expression and how it would look like in that line?

**Comment by azukaar** [comment]
> Could you just provide one example entry

https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Lemmy/cosmos-compose.json#L127
